### ISSUE TITLE
circular dependencies mongo does the server need to be a certain version? 

### ISSUE THREAD

**Issue by johnathanhawn** [Sandermoen/UnoParty#16]
> unoparty-server@1.0.0 start
> node index.js

Express and Socket.io are listening on port 9000
(node:99507) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:99507) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:99507) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:99507) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
Connected to database

seems broken

**Comment by johnathanhawn** [comment]
also Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/jhawn/Downloads/UnoParty-master/uno/unoparty-client/node_modules/babel-loader/lib/index.js:55:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
